### ISSUE TITLE
Add support for multiple var definition files

### ISSUE THREAD

**Issue by zlatko-ms** [zlatko-ms/varfiletoenv#1]
Provide a way to read the variables from more then a single file.

A possible usage would be the following : 

```yaml
    - name: Import project variables
      uses: zlatko-ms/varfiletoenv@v1
      with:
        files:
          ./test/projectvars.properties
          ./conf/myvars.config
```
