### ISSUE TITLE
Add support for override flag

### ISSUE THREAD

**Issue by zlatko-ms** [zlatko-ms/varfiletoenv#2]
Add support of a flag to control the overriding of variables from the file.

When the flag is set to true ( default value ), then the file definitions would override any variable within the workflow with same name.

When flag is set to false, then the override would be disabled and variables defined in the workflow files would not be overriden.

A possible usage would be : 

```yaml

    - name: Import project variables
      uses: zlatko-ms/varfiletoenv@v1
      with:
         override: false
         files:
          ./test/projectvars.properties
          ./conf/myvars.config

```
