### ISSUE TITLE
add support for filter on variables

### ISSUE THREAD

**Issue by zlatko-ms** [zlatko-ms/varfiletoenv#9]
Add an input paramter to support a selection of variables by their name.

The rationale is to avoid to import a bunch of variables from a (large) file , if you simply need a couple of them.

Possible usage definition : 

```
    - name: Import project variables with overriding
      uses: zlatko-ms/varfiletoenv@v1
      with:
        names: |
             version
             rtag
        paths: ./src/main/resources/tags.txt
```
would only import the variables **version** and **rtag** from the tags.txt file.
